### PR TITLE
Support pipeline plugin

### PR DESCRIPTION
**Pull request by takus**
As mentioned in #2, we need to support Pipeline plugin. I confirmed that both WebUI configuration and the following pipeline configuration work on my development environment, but please let me know if you have feedback or questions.

```
node {
    awsCodeBuild projectName: "mybuild",
        awsAccessKey: env.AWS_ACCESS_KEY_ID,
        awsSecretKey: env.AWS_SECRET_ACCESS_KEY,
        region: "us-west-2",
        sourceControlType: "remote"
}
```

### CODE REVIEW

**Comment by taoyong-ty** [comment]
Hi, 

I ran mvn install on a mac and it failed at the findbugs step. (Apache Maven 3.3.9, Java version: 1.8.0_111).

Can you fix these these issues and update your request? Thanks

[INFO] --- findbugs-maven-plugin:3.0.1:check (findbugs) @ aws-codebuild ---
[INFO] BugInstance size is 3
[INFO] Error size is 0
[INFO] Total bugs: 3
[INFO] The field CodeBuildStep$CodeBuildExecution.listener is transient but isn't set by deserialization [CodeBuildStep$CodeBuildExecution] In CodeBuildStep.java
[INFO] The field CodeBuildStep$CodeBuildExecution.ws is transient but isn't set by deserialization [CodeBuildStep$CodeBuildExecution] In CodeBuildStep.java
[INFO] Dead store to jenkinsBuildResult in CodeBuilder.perform(Run, FilePath, Launcher, TaskListener) [CodeBuilder, CodeBuilder] At CodeBuilder.java:[line 237]Another occurrence at CodeBuilder.java:[line 234]
[INFO] 


To see bug detail using the Findbugs GUI, use the following command "mvn findbugs:gui"



[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE

**Comment by taoyong-ty** [comment]
Hi @takus - Thank you very much for making this change. after fixing these minor findbugs issues, i was able to submit a codebuild job. 

1. To merge your contribution, could you confirm if you change is under Apache 2.0.
2. I was also wondering if this change support sourceControlType: "jenkins". If yes, could you please provide me an example syntax?

**Comment by taoyong-ty** [comment]
Hey @takus  could you please help answer the questions? we should be ready to merge this change once we hear back from you. Thanks.

**Comment by takus** [comment]
@taoyong-ty 
Sorry for the late reply.

> Can you fix these these issues and update your request?

I fixed last one. The others are still remain because a job failed without `transient` keyword. Many Jenkins uses transient keyword as I use (e.g. [PuppetGatlingArchiverStepExecution](https://github.com/puppetlabs/puppet-gatling-jenkins-plugin/blob/be8328bc9d39c638cf0a123beb8a3ec5bfe98c2e/src/main/java/com/puppetlabs/jenkins/plugins/puppetgatling/steps/PuppetGatlingArchiverStepExecution.java)). How should I fix it?

> could you confirm if you change is under Apache 2.0.

Yes. I confirm that my change is under Apache 2.0.

> could you please provide me an example syntax?

```
node {
    awsCodeBuild projectName: "mybuild",
        awsAccessKey: env.AWS_ACCESS_KEY_ID,
        awsSecretKey: env.AWS_SECRET_ACCESS_KEY,
        region: "us-west-2",
        sourceControlType: "jenkins"
}
```

**Comment by warmjade** [comment]
Hi Takus - 

No worries I will push a patch along with your commit.

For the transient key word. I think you created a class extends Serializable; but is not meant to be serialized. In that case, just need to add two private methods to stop the serialzation. In these methods you just need to throw the NotSerializableException.

`private void writeObject(ObjectOutputStream out) throws IOException {  
    throw new java.io.NotSerializableException(getClass().getName());  
}  
private void readObject(ObjectInputStream in) throws IOException {  
    throw new java.io.NotSerializableException(getClass().getName());  
 }`

http://stackoverflow.com/questions/2229033/making-child-classes-as-non-serializable-in-java
http://www.oracle.com/technetwork/articles/java/javaserial-1536170.html

**Comment by taoyong-ty** [comment]
Hi Takus - 

No worries I will push a patch along with your commit. You don't need to fix the findbugs issues.

To answer your question regarding the transient key word, I think you created a class extends Serializable; but is not meant to be serialized. In that case, just need to add two private methods to stop the serialzation. In these methods you just need to throw the NotSerializableException.

`private void writeObject(ObjectOutputStream out) throws IOException {  
    throw new java.io.NotSerializableException(getClass().getName());  
}  
private void readObject(ObjectInputStream in) throws IOException {  
    throw new java.io.NotSerializableException(getClass().getName());  
 }`

http://stackoverflow.com/questions/2229033/making-child-classes-as-non-serializable-in-java
http://www.oracle.com/technetwork/articles/java/javaserial-1536170.html

Again, thank you very much for your contribution.

**Comment by michaelneale** [comment]
LGTM!

**Comment by michaelneale** [comment]
In the example, is the `node` strictly required in all cases?

**Comment by takus** [comment]
@michaelneale I think so. `node` allocates executor and workspace to a job.

**Comment by taoyong-ty** [comment]
Hi takus, your commit has been merged.

I am closing this request. Thank you for your contribution!

**Pull request closed without merging**
