### PR TITLE
Fix for bad zip performance on slaves (#64)

### PR DESCRIPTION
**Pull request by Petezah**
The issue is that the zip operation is happening on the master node
but the files themselves (zipped files, and the zip file) are on the
slave.  This causes poor performance.
This fix moves the whole zip operation onto the slave node.

### CODE REVIEW

**Comment by leobaran-aws** [comment]
Thank you for this contribution! The code looks good, I just need to test your change myself. As for the build failures, your change seemed to have tripped find-bugs: 

`Exceptional return value of java.io.File.delete() ignored in ZipSourceCallable.invoke(File, VirtualChannel) [ZipSourceCallable] At ZipSourceCallable.java:[line 66]`

You can run `mvn install` to see the output of the build for yourself.

**Comment by Petezah** [comment]
Interesting; I didn't realize `mvn install` did some other things that `mvn package` and `mvn test` do.  I just pushed an update, and merged latest from master.  Thanks for taking a look!

**Comment by leobaran-aws** [comment]
Your change works for me. Can you confirm that it is under Apache 2.0 before I merge it?

**Comment by Petezah** [comment]
Yes, I have put it under that also. :)  Go for it. 👍

**Comment by leobaran-aws** [comment]
Thanks again! We'll release your change in version 0.28 this week.

**Comment by Petezah** [comment]
Awesome; thanks!  Glad to help.

**Pull request merged**
