### PR TITLE
Id/4

### PR DESCRIPTION
**Pull request by shinofara**
Hello.
Fixes issue https://github.com/awslabs/aws-codebuild-jenkins-plugin/issues/4

The priority of credentials IAM credential > Instance Profile Credential.
If `Instance Profile Credential` exists, if ` IAM credential` also exists, ` IAM credential` will be valid.

This screen shot is codebuild history.

### CODE REVIEW

**Comment by taoyong-ty** [comment]
Hi Shinofara ,

Could you please explain the use case this pull request is trying to support?  I need your help to reproduce and verify your change?

Were these builds in your screenshot submitted by a Jenkins hosted on a EC2 instance with InstanceProfileCredentialsProvider?

**Comment by shinofara** [comment]
Tnx.

> Could you please explain the use case this pull request is trying to support?
While running Jenkins on EC 2, I thought it would be inefficient to write Key and Secret for multiple jobs.
If it is ID / Secret, we have to think about the risk of copying.

> I need your help to reproduce and verify your change?
I think that it is unnecessary.

> Were these builds in your screenshot submitted by a Jenkins hosted on a EC2 instance with InstanceProfileCredentialsProvider?
I am sorry that it is confusing.
The top one is an IAM user.
Only the user name is displayed on the screen.

Secondly, it was executed with InstanceProfileCredentialsProvider.
The second is the IAM-ROLE / Instance ID.

**Comment by shinofara** [comment]
Hi @taoyong-ty 

Would you be able to help me?
I am suffering from testing using InstanceProfileCredentialsProvider now.
https://github.com/awslabs/aws-codebuild-jenkins-plugin/pull/13/files#diff-9e567bad46cc5849be516a4ea7cea218R40

How do I raise an exception internally?
Have you ever used an example using mock?

**Comment by taoyong-ty** [comment]
Hi shinora - I appended the unit test fixes and submit a new pull request https://github.com/awslabs/aws-codebuild-jenkins-plugin/pull/14 

I am closing this request right now. Could you please take a look at the new request and complete your action item listed in that thread?

**Pull request closed without merging**
