### PR TITLE
Switched to using environment variables to resolve parameters.

### PR DESCRIPTION
**Pull request by jared-rufer**
Current implementation is limited to only resolving against build parameters. 
This change allows resolving from all environment variables which include the build parameters. Was unable to get access GIT_COMMIT from another plugin. In addition this allows for $VAR and ${VAR} placeholder formats.

This contribution is under the Apache 2.0 license.

### CODE REVIEW

**Comment by dipper-github** [comment]
Thanks so much for your contribution! The code looks good--we just need to verify this change before we merge it in.

**Comment by leobaran-aws** [comment]
Thanks so much for your contribution! The code looks good--we just need to verify this change before we merge it in.

**Comment by leobaran-aws** [comment]
I wasn't able to get environment variable parameters to work. For a freestyle project, I tried executing the command `export CODEBUILD_PROJECT=project-name` in a shell script step followed by a CodeBuild step with project name "$CODEBUILD_PROJECT". For a pipeline, I included the following block above the awsCodeBuild step (with `projectName: '$CODEBUILD_PROJECT'`):
``` 
environment {
      CODEBUILD_PROJECT = 'project-name'
}
```

I should add I tried both $VAR and ${VAR}. Any advice?

**Comment by jared-rufer** [comment]
The way environment variables can be configured during the execution of a build is not straight forward or well documented. In addition environment variables are isolated from step to step. However there are plugins like [EnvInject](https://wiki.jenkins.io/display/JENKINS/EnvInject+Plugin) that can add environment variables from a previous step by outputting a file that the EnvInject can digest. Another example is the GIT SCM plugin which updates environment variables in the build through plugin extension / descriptor api.

**Comment by leobaran-aws** [comment]
Ahh I see. Thanks so much for your contribution--we'll merge this in and release it in version 0.15.

**Pull request merged**
